// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowCapabilityPack } from "./DevflowCapabilityPack";
import type { DevflowCapabilityPackRunStatus } from "./DevflowCapabilityPackRunStatus";

export type DevflowCapabilityPackRunResponse = { pack: DevflowCapabilityPack, status: DevflowCapabilityPackRunStatus, summary: string, artifact: DevflowArtifact | null, };
