// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowRunOutputSource } from "./DevflowRunOutputSource";

export type DevflowRunOutputDeltaNotification = { projectId: string, taskId: string, runId: string, source: DevflowRunOutputSource, delta: string, };
