// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifact } from "./DevflowArtifact";
import type { DevflowPolicyPack } from "./DevflowPolicyPack";

export type DevflowPolicyPackApplyResponse = { pack: DevflowPolicyPack, applied: boolean, requiredArtifacts: Array<string>, diagnostics: Array<string>, artifact: DevflowArtifact | null, };
