// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowRunStatus } from "./DevflowRunStatus";

export type DevflowRun = { id: string, taskId: string, agentId: string, threadId: string | null, turnId: string | null, status: DevflowRunStatus, startedAt: bigint, completedAt: bigint | null, input: string, streamSummary: string | null, commandIds: Array<string>, artifactIds: Array<string>, exitReason: string | null, };
