// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowWorktreeStatus } from "./DevflowWorktreeStatus";

export type DevflowWorktree = { id: string, taskId: string, projectId: string, repoRoot: string, rootPath: string, cwdPath: string, branch: string, baseBranch: string | null, baseCommit: string, headCommit: string | null, managed: boolean, status: DevflowWorktreeStatus, createdAt: bigint, updatedAt: bigint, };
