// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowWatchdogAlertSeverity } from "./DevflowWatchdogAlertSeverity";
import type { DevflowWatchdogStatus } from "./DevflowWatchdogStatus";

export type DevflowWatchdogAlert = { id: string, status: DevflowWatchdogStatus, severity: DevflowWatchdogAlertSeverity, projectId: string | null, taskId: string | null, runId: string | null, message: string, createdAt: bigint, };
