// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskStatus } from "./DevflowTaskStatus";

export type DevflowTaskListParams = { projectId?: string | null, status?: DevflowTaskStatus | null, assignedAgentId?: string | null, cursor?: string | null, limit?: number | null, };
