// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifact } from "./DevflowArtifact";
import type { DevflowReleaseSubmitMode } from "./DevflowReleaseSubmitMode";
import type { DevflowReleaseSubmitStatus } from "./DevflowReleaseSubmitStatus";

export type DevflowReleaseSubmitResponse = { status: DevflowReleaseSubmitStatus, summary: string, blockers: Array<string>, commitMessageArtifact: DevflowArtifact, prBodyArtifact: DevflowArtifact, releaseNoteArtifact: DevflowArtifact, approval: DevflowApproval | null, publishReportArtifact: DevflowArtifact | null, mode: DevflowReleaseSubmitMode, remote: string | null, branch: string | null, command: string, exitCode: number | null, outputSummary: string, publishedAt: bigint | null, };
