// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowTaskStatus = "planned" | "running" | "paused" | "ready_for_review" | "ready_to_merge" | "failed" | "blocked" | "cancelled";
