// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowQualityGateKind } from "./DevflowQualityGateKind";
import type { DevflowQualityGateStatus } from "./DevflowQualityGateStatus";

export type DevflowQualityGate = { id: string, taskId: string, runId: string, kind: DevflowQualityGateKind, status: DevflowQualityGateStatus, command: string, cwd: string, exitCode: number | null, durationMs: bigint | null, summary: string | null, artifactId: string | null, waivedReason: string | null, createdAt: bigint, updatedAt: bigint, };
