// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowRun } from "./DevflowRun";
import type { DevflowTask } from "./DevflowTask";

export type DevflowTaskStartResponse = { task: DevflowTask, run: DevflowRun, };
