// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowWorktreeDiffUpdatedNotification = { projectId: string, taskId: string, runId: string, worktreeId: string | null, artifactId: string, diff: string, };
