// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskStatus } from "./DevflowTaskStatus";

export type DevflowTaskDispatchSkipped = { taskId: string, title: string, status: DevflowTaskStatus, reason: string, };
