// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskKind } from "./DevflowTaskKind";
import type { DevflowTaskRiskLevel } from "./DevflowTaskRiskLevel";

export type DevflowTaskCreateParams = { projectRoot: string, title: string, objective: string, kind: DevflowTaskKind, riskLevel: DevflowTaskRiskLevel, triggerSource?: string | null, dependencies?: Array<string> | null, assignedAgentId?: string | null, };
