// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskKind } from "./DevflowTaskKind";
import type { DevflowTaskRiskLevel } from "./DevflowTaskRiskLevel";
import type { DevflowTaskStatus } from "./DevflowTaskStatus";

export type DevflowTask = { id: string, projectId: string, title: string, objective: string, triggerSource: string | null, status: DevflowTaskStatus, kind: DevflowTaskKind, riskLevel: DevflowTaskRiskLevel, dependencies: Array<string>, assignedAgentId: string | null, worktreeId: string | null, contextPackId: string | null, runIds: Array<string>, artifactIds: Array<string>, createdAt: bigint, updatedAt: bigint, };
