// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifact } from "./DevflowArtifact";
import type { DevflowReleasePrepStatus } from "./DevflowReleasePrepStatus";

export type DevflowReleasePrepCreateResponse = { status: DevflowReleasePrepStatus, summary: string, blockers: Array<string>, commitMessageArtifact: DevflowArtifact, prBodyArtifact: DevflowArtifact, releaseNoteArtifact: DevflowArtifact, };
