// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowApprovalKind } from "./DevflowApprovalKind";
import type { DevflowApprovalStatus } from "./DevflowApprovalStatus";

export type DevflowApproval = { id: string, projectId: string, taskId: string, runId: string, qualityGateId: string | null, requestId: string, threadId: string, turnId: string, itemId: string, kind: DevflowApprovalKind, status: DevflowApprovalStatus, reason: string | null, command: string | null, cwd: string | null, filePaths: Array<string>, requestedPermissions: RequestPermissionProfile | null, respondedAt: bigint | null, decision: DevflowApprovalDecision | null, createdAt: bigint, };
