// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowArtifactDeliverParams = { id: string, targetAgentId: string, destination: string, message?: string | null, };
