// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTask } from "./DevflowTask";
import type { DevflowWorktree } from "./DevflowWorktree";

export type DevflowWorktreeMergeResponse = { merged: boolean, worktree: DevflowWorktree, task: DevflowTask, conflicts: Array<string>, };
