// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowQualityGateKind = "format" | "lint" | "typecheck" | "targeted_test" | "integration_test" | "snapshot" | "build" | "review" | "gstack_health" | "gstack_browser_qa" | "gstack_benchmark" | "gstack_canary" | "gstack_watchdog";
