// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifactKind } from "./DevflowArtifactKind";

export type DevflowArtifact = { id: string, taskId: string, runId: string, kind: DevflowArtifactKind, title: string, path: string, mimeType: string, summary: string, createdAt: bigint, };
