// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowPackStatus } from "./DevflowPackStatus";

export type DevflowCapabilityPack = { id: string, name: string, sourcePath: string | null, status: DevflowPackStatus, capabilities: Array<string>, diagnostics: Array<string>, };
