// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifact } from "./DevflowArtifact";

export type DevflowArtifactListResponse = { data: Array<DevflowArtifact>, nextCursor: string | null, };
