// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowTaskDispatchBlocked = { taskId: string, title: string, dependencies: Array<string>, reason: string, };
