// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowAgent } from "./DevflowAgent";

export type DevflowAgentRestartResponse = { agent: DevflowAgent, restarted: boolean, message: string, };
