// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowQualityGateKind } from "./DevflowQualityGateKind";

export type DevflowQualityGateRunParams = { taskId: string, kind?: DevflowQualityGateKind | null, commandOverride?: string | null, };
