// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Distinguishes the Codex-owned Devflow main path from legacy compatibility
 * adapters that are exposed for migration and diagnostics.
 */
export type DevflowAgentLane = "main" | "legacy";
