// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowWatchdogAlert } from "./DevflowWatchdogAlert";
import type { DevflowWatchdogStatus } from "./DevflowWatchdogStatus";

export type DevflowWatchdogReadResponse = { status: DevflowWatchdogStatus, alerts: Array<DevflowWatchdogAlert>, checkedAt: bigint, };
