// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowArtifactKind = "context_pack" | "diff" | "delivery_receipt" | "output_archive" | "quality_gate_output" | "report" | "review_report" | "run_summary";
