// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowWatchdogAlertSeverity } from "./DevflowWatchdogAlertSeverity";
import type { DevflowWatchdogStatus } from "./DevflowWatchdogStatus";

export type DevflowWatchdogAlertsParams = { status?: DevflowWatchdogStatus | null, severity?: DevflowWatchdogAlertSeverity | null, cursor?: string | null, limit?: number | null, };
