// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifactKind } from "./DevflowArtifactKind";

export type DevflowArtifactListParams = { taskId?: string | null, runId?: string | null, kind?: DevflowArtifactKind | null, cursor?: string | null, limit?: number | null, };
