// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowArtifact } from "./DevflowArtifact";
import type { DevflowArtifactDeliveryStatus } from "./DevflowArtifactDeliveryStatus";

export type DevflowArtifactDeliverResponse = { artifact: DevflowArtifact, receiptArtifact: DevflowArtifact | null, approval: DevflowApproval | null, targetAgentId: string, destination: string, command: string, exitCode: number | null, status: DevflowArtifactDeliveryStatus, outputSummary: string, deliveredAt: bigint | null, };
