// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskDispatchBlocked } from "./DevflowTaskDispatchBlocked";
import type { DevflowTaskDispatchSkipped } from "./DevflowTaskDispatchSkipped";
import type { DevflowTaskDispatchStarted } from "./DevflowTaskDispatchStarted";

export type DevflowWatchdogReconcileResponse = { projectId: string, summary: string, started: Array<DevflowTaskDispatchStarted>, skipped: Array<DevflowTaskDispatchSkipped>, blocked: Array<DevflowTaskDispatchBlocked>, integratorArtifact: DevflowArtifact | null, };
