// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowSupportBundle = { id: string, projectId: string, path: string, mimeType: string, summary: string, diagnostics: Array<string>, createdAt: bigint, };
