// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowTaskRiskLevel } from "./DevflowTaskRiskLevel";

export type DevflowTaskPlanParams = { projectRoot: string, title: string, objective: string, riskLevel: DevflowTaskRiskLevel, maxTasks?: number | null, };
