// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowAgentRuntime } from "./DevflowAgentRuntime";
import type { DevflowAgentStatus } from "./DevflowAgentStatus";

export type DevflowAgent = { id: string, name: string, runtime: DevflowAgentRuntime, roles: Array<string>, rootPath: string | null, launchCommand: string | null, status: DevflowAgentStatus, capabilities: Array<string>, diagnostics: Array<string>, lastError: string | null, };
