// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevflowProject = { id: string, name: string, rootPath: string, gitRemote: string | null, defaultBranch: string | null, currentBranch: string | null, isTrusted: boolean, testCommands: Array<string>, detectedDocs: Array<string>, diagnostics: Array<string>, };
