// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevflowPackStatus } from "./DevflowPackStatus";
import type { DevflowTaskRiskLevel } from "./DevflowTaskRiskLevel";

export type DevflowPolicyPack = { id: string, name: string, sourcePath: string | null, status: DevflowPackStatus, policies: Array<string>, appliesToRiskLevels: Array<DevflowTaskRiskLevel>, diagnostics: Array<string>, };
