// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthStyle } from "./ProviderAuthStyle";
import type { ProviderEnvHeaderInput } from "./ProviderEnvHeaderInput";
import type { ProviderHeaderInput } from "./ProviderHeaderInput";
import type { ProviderWireApi } from "./ProviderWireApi";

export type ProviderConfigParams = { displayName: string, baseUrl: string, wireApi: ProviderWireApi, authStyle: ProviderAuthStyle, envKey?: string | null, apiKey?: string | null, requiresOpenaiAuth: boolean, supportsWebsockets: boolean, requestMaxRetries?: bigint | null, streamMaxRetries?: bigint | null, streamIdleTimeoutMs?: bigint | null, websocketConnectTimeoutMs?: bigint | null, headers?: Array<ProviderHeaderInput> | null, envHeaders?: Array<ProviderEnvHeaderInput> | null, };
