// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderTestConnectionErrorCode = "MISSING_API_KEY" | "INVALID_BASE_URL" | "FAIL_AUTH" | "FAIL_NETWORK" | "FAIL_DNS" | "FAIL_TLS" | "FAIL_ENDPOINT" | "FAIL_MODEL" | "FAIL_STREAM" | "FAIL_SCHEMA" | "FAIL_TOOL" | "UNSUPPORTED_WIRE_API";
