// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderTestConnectionChecks } from "./ProviderTestConnectionChecks";
import type { ProviderTestConnectionTarget } from "./ProviderTestConnectionTarget";

export type ProviderTestConnectionParams = { target: ProviderTestConnectionTarget, model: string, checks?: ProviderTestConnectionChecks | null, };
