// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderHeaderValueSource } from "./ProviderHeaderValueSource";

export type ProviderHeaderSummary = { name: string, valueSource: ProviderHeaderValueSource, value: string, };
