// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConfigParams } from "./ProviderConfigParams";

export type ProviderTestConnectionTarget = { "type": "saved", id: string, } | { "type": "draft", id: string, provider: ProviderConfigParams, };
