// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderTestConnectionCheckResult } from "./ProviderTestConnectionCheckResult";

export type ProviderTestConnectionResponse = { ok: boolean, summary: string, results: Array<ProviderTestConnectionCheckResult>, };
