// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderConnectionCheck } from "./ProviderConnectionCheck";
import type { ProviderTestConnectionErrorCode } from "./ProviderTestConnectionErrorCode";

export type ProviderTestConnectionCheckResult = { check: ProviderConnectionCheck, ok: boolean, errorCode: ProviderTestConnectionErrorCode | null, message: string | null, httpStatus: number | null, };
