// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderAuthStyle } from "./ProviderAuthStyle";
import type { ProviderHeaderSummary } from "./ProviderHeaderSummary";
import type { ProviderSource } from "./ProviderSource";
import type { ProviderWireApi } from "./ProviderWireApi";

export type Provider = { id: string, displayName: string, source: ProviderSource, builtinKind: string | null, baseUrl: string | null, wireApi: ProviderWireApi, authStyle: ProviderAuthStyle, envKey: string | null, hasApiKey: boolean, supportsWebsockets: boolean, requiresOpenaiAuth: boolean, requestMaxRetries: bigint | null, streamMaxRetries: bigint | null, streamIdleTimeoutMs: bigint | null, websocketConnectTimeoutMs: bigint | null, headers: Array<ProviderHeaderSummary>, isDefault: boolean, };
