// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderPreferencesScope } from "./ProviderPreferencesScope";

export type ProviderPreferencesUpdateParams = { defaultProvider: string, defaultModel: string | null, configScope: ProviderPreferencesScope, cwd?: string | null, };
